# Generated by Django 4.1.5 on 2023-04-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tours',
            name='date_start',
            field=models.DateField(),
        ),
    ]
